PRODUCT_PACKAGES += \
    ContactsProviderOverlay_GMS \
    framework-resOverlay_GMS \
    GlanceableHubConfigOverlay \
    GlanceableHubSettingsConfigOverlay \
    GlanceableHubSettingsConfigOverlay2022 \
    GlanceableHubSysuiConfigOverlay \
    GoogleConfigOverlay_GMS \
    GoogleWebViewOverlay_GMS \
    PixelConfigOverlay2018_GMS \
    PixelConfigOverlay2019Midyear_GMS \
    PixelConfigOverlay2021_GMS \
    PixelConfigOverlayCommon_GMS \
    PixelDocumentsUIGoogleOverlay_GMS \
    PixelSetupWizardOverlay2024_GMS \
    PixelSetupWizardOverlayExpressive_GMS \
    SettingsOverlay_GMS \
    SettingsProviderOverlay_GMS \
    SystemUIGXOverlay_GMS \
    SystemUIOverlay_GMS \
    TelecomOverlayDeprecatedGoogle \
    TelecomOverlayZumaproGoogle \
    TeleServiceOverlay_GMS \
